name: california
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - geopandas
  - shapely
  - pyproj
  - fiona
  - pydeck
  - streamlit
  - requests
  - pip:
      - xgboost
      - lightgbm
      - plotly
